# ansible/site.yml
- name: Configure web server and deploy app
  hosts: webservers
  become: yes
  vars:
    app_src: "../app"
    app_dest: "/var/www/html/index.html"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      copy:
        src: "{{ app_src }}/index.html"
        dest: "{{ app_dest }}"
        owner: www-data
        group: www-data
        mode: '0644'
